// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCioqUPaf8xNIFSkMZ3QFCuK0ijgj7gqrU',
    appId: '1:23368243848:web:9e8d5a0daada040c6ddd3d',
    messagingSenderId: '23368243848',
    projectId: 'campus-lost-found-4d4b1',
    authDomain: 'campus-lost-found-4d4b1.firebaseapp.com',
    storageBucket: 'campus-lost-found-4d4b1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUz_wjt8YVprRHihgykFLvDZQjtksbpuI',
    appId: '1:23368243848:android:063d3acf2125f9b06ddd3d',
    messagingSenderId: '23368243848',
    projectId: 'campus-lost-found-4d4b1',
    storageBucket: 'campus-lost-found-4d4b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVxw7NW9-l4PoP_wVch1O0UVmxyMYL8bI',
    appId: '1:23368243848:ios:0503a6d92889141d6ddd3d',
    messagingSenderId: '23368243848',
    projectId: 'campus-lost-found-4d4b1',
    storageBucket: 'campus-lost-found-4d4b1.firebasestorage.app',
    iosBundleId: 'com.example.campusLostFound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCioqUPaf8xNIFSkMZ3QFCuK0ijgj7gqrU',
    appId: '1:23368243848:web:4c24ee44b1df41a56ddd3d',
    messagingSenderId: '23368243848',
    projectId: 'campus-lost-found-4d4b1',
    authDomain: 'campus-lost-found-4d4b1.firebaseapp.com',
    storageBucket: 'campus-lost-found-4d4b1.firebasestorage.app',
  );
}
